name: Build
on:
  workflow_dispatch:
  push:
    branches:
    - 'master'
    paths-ignore:
    - '**.md'
    - '**.opam'
    - 'LICENSE'
  pull_request:
    paths-ignore:
    - '**.md'
    - '**.opam'
    - 'LICENSE'
concurrency:
  group: "${{ github.workflow }}-${{ github.event.pull_request.number || github.head_ref || github.ref }}"
  cancel-in-progress: true
permissions:
  contents: read
env:
  OCAML_COMILER_VERSION: "4.14.2"
  JOBS: 4
  TMPDIR: /tmp
jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Checkout branch ${{ github.ref_name }}
        uses: actions/checkout@v4

      - run: sudo apt-get update
      - name: Restore opam cache
        id: opam-cache
        uses: actions/cache@v4
        with:
          path: "~/.opam"
          key: opam-${{env.OCAML_COMILER_VERSION}}-${{hashFiles('.github/coq-lambda-box-extraction.opam.locked')}}
          restore-keys: |
            opam-${{env.OCAML_COMILER_VERSION}}-

      - name: Set up OCaml
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: ${{env.OCAML_COMILER_VERSION}}

      - name: Build dependencies
        #if: ${{ !steps.opam-cache.outputs.cache-hit }}
        run: |
          opam repo add coq-released https://coq.inria.fr/opam/released
          opam install --deps-only -j${{ env.JOBS }} .github/coq-lambda-box-extraction.opam.locked
          opam clean -a -c -s --logs

      - name: Set up environment
        run: |
          echo "::group::Setting up problem matcher"
          echo "::add-matcher::./.github/coq-errors.json"
          echo "::endgroup::"

      - name: Build
        run: |
          opam exec -- make -j${{ env.JOBS }}

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: 1.85.0

      - name: Set up Elm
        run: |
          curl -L -o elm.gz https://github.com/elm/compiler/releases/download/0.19.1/binary-for-linux-64-bit.gz
          gunzip elm.gz
          sudo chmod +x elm
          sudo mv elm /usr/local/bin/
      - name: Set up elm-test
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Set up elm-test
        run: |
          npm install -g elm-test@0.19.1-revision9

      - name: Test extraction
        run: |
          echo "::group::Running tests"
          eval $(opam env) && cd test && npm install && npm run test
          echo "::endgroup::"
